
version: '3.8'

services:
  user-management-service:
    build: .
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - HTTP_PORT=8081
      - GRPC_PORT=8082
      - DATABASE_URL=your_database_url
      - JWT_SECRET=your_jwt_secret
      - SHUTDOWN_TIMEOUT=10s
