
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-gateway
spec:
  selector:
    matchLabels:
      app: event-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: event-gateway
    spec:
      containers:
      - name: event-gateway
        image: event-gateway:latest
        ports:
        - containerPort: 50051
